import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Products Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${geistSans.variable} ${geistMono.variable} ${styles.main}`}>
        <h1 className={styles.title}>Home App</h1>
        <p className={styles.description}>
          Bienvenido a nuestra aplicación. Explora nuestros{" "}
          <Link href="/productos" className={styles.link}>
            productos
          </Link>.
        </p>
      </main>
    </>
  );
}